name: Expo

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: { }

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby 2.7
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.6
          bundler-cache: true
      - uses: fac/ruby-gem-setup-credentials-action@v2
        with:
          token: ${{ secrets.RUBYGEMS_AUTH_TOKEN }}

      - name: Run tests
        run: bundle exec rake

      - name: Build
        run: bundle exec rake build

      - name: Publish to RubyGems
        if: github.ref == 'refs/heads/main'
        uses: fac/ruby-gem-push-action@v2
        with:
          key: github
